# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Bar.destroy_all

bars = Bar.create([{
	biz_id: 0,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[0].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[0].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[0].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[0].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:0}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:0}).region.center.longitude},
	{
	biz_id: 1,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[1].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[1].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[1].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[1].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:1}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:1}).region.center.longitude},
	{
	biz_id: 2,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[2].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[2].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[2].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[2].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:2}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:2}).region.center.longitude},
	{
	biz_id: 3,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[3].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[3].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[3].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[3].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:3}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:3}).region.center.longitude},
	{
	biz_id: 4,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[4].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[4].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[4].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[4].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:4}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:4}).region.center.longitude},
	{
	biz_id: 5,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[5].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[5].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[5].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[5].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:5}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:5}).region.center.longitude},
	{
	biz_id: 6,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[6].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[6].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[6].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[6].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:6}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:6}).region.center.longitude},
	{
	biz_id: 7,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[7].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[7].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[7].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[7].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:7}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:7}).region.center.longitude},
	{
	biz_id: 8,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[8].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[8].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[8].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[8].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:8}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:8}).region.center.longitude},
	{
	biz_id: 9,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[9].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[9].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[9].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[9].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:9}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:9}).region.center.longitude},
	{
	biz_id: 10,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[10].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[10].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[10].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[10].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:10}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:10}).region.center.longitude},
	{
	biz_id: 11,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[11].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[11].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[11].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[11].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:11}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:11}).region.center.longitude},
	{
	biz_id: 12,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[12].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[12].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[12].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[12].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:12}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:12}).region.center.longitude},
	{
	biz_id: 13,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[13].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[13].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[13].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[13].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:13}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:13}).region.center.longitude},
	{
	biz_id: 14,
	name: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[14].name,
	street: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[14].location.display_address[0],
	city_state_zip: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[14].location.display_address[2],
	day: 'tuesday',
	time: '8:00pm',
	theme: 'general',
	web: Yelp.client.search('Santa Monica', {term:'bar trivia'}).businesses[14].url,
	lat: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:14}).region.center.latitude,
	lon: Yelp.client.search('Santa Monica', {term:'bar trivia',limit: 1, offset:14}).region.center.longitude}
])